version: '3'

volumes:
  jobkhuzi_dev_postgres_data: { }
  jobkhuzi_dev_postgres_data_backups: { }
  postgres_data: { }
  postgres_data_backups: { }

services:
  postgres_dev:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: explorer_dev_postgres
    volumes:
      - jobkhuzi_dev_postgres_data:/var/lib/postgresql/data:Z
      - jobkhuzi_dev_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres
    restart: always
    ports:
      - 5432:5432

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: it_jobs_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: always
    ports:
      - 15432:5432
