version: '3'

volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: explorer_dev_postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
      - dev_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres
    restart: always
