version: '3.8'

volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}
  prod_postgres_data: {}
  prod_postgres_data_backups: {}

services:
  postgres_dev:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: explorer_dev_postgres
    container_name: postgres_dev
    restart: always
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
      - dev_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres
    ports:
      - 5432:5432